version: '3.4'

services:
  sql:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=SERVERPASSWORD
      - POSTGRES_USER=SERVER
      - POSTGRES_DB=SERVER
      - PGDATA=./.database/postgres/data
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
