version: '3.4'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    networks:
      bridge:
        ipv4_address: 10.10.10.4

  sql:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=SERVERPASSWORD
      - POSTGRES_USER=SERVER
      - POSTGRES_DB=SERVER
      - PGDATA=./.database/postgres/data
    expose:
      - 5432
    networks:
      bridge:
        ipv4_address: 10.10.10.3

  server:
    image: ${DOCKER_REGISTRY-}notify-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      bridge:
        ipv4_address: 10.10.10.2
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    expose:
      - 80
    depends_on:
      - sql
      - proxy

networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
        # - gateway: 10.10.10.1
