version: '2.2'

services:
  sql:
    restart: always
    image: postgres:latest
    #    volumes:
    #      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SERVERPASSWORD
      - POSTGRES_USER=SERVER
      - POSTGRES_DB=SERVER
      - PGDATA=./.database/postgres/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

